# ==========================================
# Application Configuration - DevOps Simulator
# ==========================================

# === Production Configuration (Active) ===
production:
  application:
    name: DevOpsSimulator
    version: 1.0.0
    environment: production

  server:
    host: 0.0.0.0
    port: 8080
    ssl_enabled: true

  logging:
    level: INFO
    format: json

# === Development Configuration ===
development:
  enabled: true
  application:
    name: DevOpsSimulator
    version: 2.0.0-beta
    environment: development

  server:
    host: localhost
    port: 3000
    hot_reload: true
    debug_mode: true
    mock_apis: true

  logging:
    level: DEBUG
    format: text

# === Experimental Configuration (AI-Enhanced) ===
experimental:
  version: 3.0.0-experimental
  environment: testing

  server:
    multi_port: [9000, 9001, 9002]

  logging:
    output: /var/log/experimental.log
    ai_analysis: enabled

  database:
    host: cluster.example.com
    port: 5432
    name: devops_experimental
    distributed: true

  features:
    auto_scaling: advanced
    load_balancer: ai-optimized
    backup_enabled: true
    chaos_engineering: enabled

  ai_features:
    predictive_scaling: true
    anomaly_detection: true
    auto_optimization: true
    model_version: "v2.1.0"

  cloud_providers:
    - aws
    - azure
    - gcp
    - digitalocean

  security:
    zero_trust: enabled
    encryption: AES-256
    audit_logging: comprehensive
